spring.application.name=SafeZoneBackend
server.port=8080
spring.cloud.azure.cosmos.endpoint=""
spring.cloud.azure.cosmos.key=""
spring.cloud.azure.cosmos.database=SafeZone
spring.cloud.azure.cosmos.populate-query-metrics=false
# Logs
logging.level.com.azure.cosmos=WARN
logging.level.com.azure.core=WARN
logging.level.SafeZone=INFO
# JWT Configuration (Base64 encoded secret)
jwt.secret=test-secret